/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    subscribers: Subscriber;
    'subscriber-lists': SubscriberList;
    campaigns: Campaign;
    templates: Template;
  };
  globals: {};
}
export interface User {
  id: string;
  firstname: string;
  lastname: string;
  roles: 'editor' | 'admin' | 'developer';
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Subscriber {
  id: string;
  fullname: string;
  email: string;
  lists?: string[] | SubscriberList[];
  createdAt: string;
  updatedAt: string;
}
export interface SubscriberList {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}
export interface Campaign {
  id: string;
  name: string;
  type?: 'lists' | 'individual';
  lists?: {
    lists: string[] | SubscriberList[];
  };
  individuals?: {
    subscribers: string[] | Subscriber[];
  };
  subject: string;
  body: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Template {
  id: string;
  name: string;
  subject: string;
  html: string;
  text: string;
  createdAt: string;
  updatedAt: string;
}
